### ISSUE TITLE
Bug when defining fixtures

### ISSUE THREAD

**Issue by wildsurfer** [mongator/factory#10]
Lets's say I have this schema:

``` php
return array(
    'collection' => 'Athlete',
    'fields' => array(
        'firstName' => 'string'
    )
);
```

This code will return array with data

``` php
$modelName = 'Model\Athlete';
$factory->define('MyFixture', $modelName, array(
    'firstName' => 'MyName'
));
$document = $factory->create('MyFixture');
$testData = $document->toArray();
```

But if I change my code to separate PHP names from Mongo names $testData array will have empty values.

``` php
return array(
    'collection' => 'Athlete',
    'fields' => array(
        'firstName' => array(
            'type' => 'string',
            'dbName' => 'first_name'
        ),
    )
);
```

**Comment by wildsurfer** [comment]
Workaround for me was to change this line
https://github.com/mongator/factory/blob/master/src/Mongator/Factory/Blueprint.php#L73

From

``` php
 $data = $this->build($overrides);
```

To

``` php
 $data = $this->build($overrides, false);
```

**Comment by mcuadros** [comment]
Hummmm i will take a look, is possible that this fail because we dont use dbName feature.

I will take a looks asap.

**Comment by wildsurfer** [comment]
Thanks, man!

**Comment by mcuadros** [comment]
Sorry about the delay but this is solved.

Thanks!

**Comment by wildsurfer** [comment]
Awesome!
